services:
  builder:
    build: .
    volumes:
      - ./index.html:/build/index.html
      - ./dist:/dist  # ✅ this is the critical line
    command: ["/bin/sh", "-c", "/dist/launch.sh; sleep infinity"]